### ISSUE TITLE
[PE-D][Tester C] `CLEAR` clears category data instead of just expense logs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-2/tp#184]
_This issue assumes the functionality specified in the User Guide is accurate as of the current version_

![image.png](https://raw.githubusercontent.com/chia-yh/ped/main/files/5ddb999b-9540-4ca3-9bc6-3f0ed0adeb32.png)

Steps to reproduce:
1. launch FastTrack with default data
2. `CLEAR`
3. `lcat`

    Expected: lists existing categories;

    Actual: no categories shown;

Using the `CLEAR` command wipes existing categories in addition to expenses and recurring expenses. Could inconvenience users who want to keep existing categories and clear only the existing expenses.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chia-yh/ped#7

**Comment by shirsho-12** [comment]
Clarify functionality of the command in the UG
