### ISSUE TITLE
[PE-D][Tester D] Functionality Bug - Find function requires the exact keyword

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-2/tp#195]
![image.png](https://raw.githubusercontent.com/daniellingzy/ped/main/files/f58e96d4-a8e7-4881-82fb-88ebc300afa6.png)

in the event that I have a spending named "milk" and i enter "find m" as shown above, the application does not return the milk expense. This is problematic as your target audience may not remember exactly the expenses' names that they recorded, and if they have to use "list feature" to find out the exact names of these expenses, that defeats the purpose of the find feature, as it would then make more sense for them to access the expense object from the "displayed screen" instead, after calling list.

Hence I would suggest enhancing this feature to find any expenses' names that contains the given keyword.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: daniellingzy/ped#7

**Comment by shirsho-12** [comment]
This is as defined in the UG. The application at its current state only works with full matches.
